linters:
  SelectorFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  PropertySortOrder:
    enabled: false
  VendorPrefix:
    enabled: false
  LeadingZero:
    enabled: false
  ColorKeyword:
    enabled: false
  Comment:
    enabled: false
  StringQuotes:
    style: double_quotes
  SpaceAfterPropertyColon:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
