linters:
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
  PropertySortOrder:
    enabled: false
  SelectorFormat:
    ignored_names: [W, N, E, S]
  SpaceAfterComma:
    style: at_least_one_space
  SpaceAfterPropertyColon:
    enabled: false
  StringQuotes:
    style: double_quotes
  UnnecessaryMantissa:
    enabled: false
