linters:
  LeadingZero:
    enabled: false
  PropertySortOrder:
    enabled: false
  SpaceAfterComma:
    style: at_least_one_space
  SpaceAfterPropertyColon:
    enabled: false
  StringQuotes:
    style: double_quotes
  UnnecessaryMantissa:
    enabled: false

  SelectorFormat:
    enabled: false
  Comment:
    enabled: false
