linters:
  PropertySortOrder:
    enabled: false
  SpaceAfterComma:
    style: at_least_one_space
  SpaceAfterPropertyColon:
    enabled: false
  StringQuotes:
    style: double_quotes
  UnnecessaryMantissa:
    enabled: false

  SelectorFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  VendorPrefix:
    enabled: false
  LeadingZero:
    enabled: false
  ColorKeyword:
    enabled: false
  Comment:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
